python generate_clg.py -g bio -m mistral -mt
python generate_clg.py -g prof -m mistral -mt
python generate_clg.py -g rec -m mistral -mt
python generate_clg.py -g bio -m chatgpt -mt
python generate_clg.py -g prof -m chatgpt -mt
python generate_clg.py -g rec -m chatgpt -mt
python generate_clg.py -g bio -m llama3 -mt
python generate_clg.py -g prof -m llama3 -mt
python generate_clg.py -g rec -m llama3 -mt